/* Automatically generated by './build/bin/build-entry.js' */

import Welcome from '../packages/welcome/index.js';


const components = [
    Welcome
];

const install = function(Vue, opts = {}) {

    components.map(component => {
        Vue.component(component.name, component);
    });


    const ELEMENT = {};
    ELEMENT.size = opts.size || '';

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
    install(window.Vue);
}

module.exports = {
    version: '1.0.0'
};

module.exports.default = module.exports;
